max_jobs: 1

image: Visual Studio 2019

cache:
  - '%LocalAppData%\NuGet\v3-cache'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

install:
  - cmd: dotnet tool install -g Cake.Tool --version 0.33.0

build_script:
  - cmd: dotnet cake --target=Full

test: off

artifacts:
  - path: outputs\*.nupkg
    name: packages

deploy:
  - provider: Environment
    name: MyGet EMG Public
    on:
      branch: master
  - provider: Environment
    name: NuGet EMG
    on:
      branch: master
      appveyor_repo_tag: true
